version: "3.1"

services:

    db:
        image: mysql:8.0
        container_name: local-db
        restart: always
        ports: 
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - ${VOLUME_DATABASE}:/var/lib/mysql
        networks:
            - default

    nginx:
        image: nginx:1.20-alpine
        container_name: local-nginx
        restart: always
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - ${VOLUME_WORKSPACE}:/var/www
            - ${VOLUME_NGINX_CONFIG}:/etc/nginx/conf.d
        networks:
            default:
                aliases:
                    - ddi.test

    php:
        image: local-php
        container_name: local-php
        restart: always
        working_dir: /var/www
        build:
            args:
                user: ${USER_NAME}
            context: ./dockerfiles/php-74
            dockerfile: Dockerfile
        volumes:
            - ${VOLUME_WORKSPACE}:/var/www
            - ${VOLUME_PHP_INI}:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - default

    redis:
        image: redis:7.0.7-alpine
        container_name: local-redis
        restart: always
        volumes:
            - ${VOLUME_REDIS_CONFIG}:/usr/local/etc/redis/redis.conf
        networks:
            - default
        ports: 
            - 6379:6379

    node:
        image: local-node
        container_name: local-node
        restart: always
        working_dir: /srv
        build:
            args:
                name: ${GIT_USER_NAME}
                email: ${GIT_USER_EMAIL}
                ngversion: ${ANGULAR_VERSION}
            context: ./dockerfiles/node
            dockerfile: Dockerfile
        volumes:
            - ${VOLUME_WORKSPACE}:/srv
        command: tail -f /dev/null
        networks:
            - default
        ports: 
            - 4200:4200

    mailhog:
        image: mailhog/mailhog:v1.0.1
        container_name: local-mail
        restart: always
        networks:
            - default
        ports: 
            - 1025:1025
            - 8025:8025


networks:
    default:
        driver: bridge