version: "3.1"

services:

    db:
        image: mysql:8.0
        container_name: local-db
        restart: always
        ports: 
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - ${VOLUME_DATABASE}:/var/lib/mysql
        networks:
            - default

    nginx:
        image: nginx:1.20-alpine
        container_name: local-nginx
        restart: always
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - ${VOLUME_WORKSPACE}:/var/www
            - ${VOLUME_NGINX_CONFIG}:/etc/nginx/conf.d
        networks:
            default:
                aliases:
                    - ddi.test

    php:
        image: local-php
        container_name: local-php
        restart: always
        working_dir: /var/www
        build:
            args:
                user: ${USER_NAME}
                uid: ${USER_UID}
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ${VOLUME_WORKSPACE}:/var/www
            - ${VOLUME_PHP_INI}:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - default

    redis:
        image: redis:6.2.6-alpine
        container_name: local-redis
        restart: always
        volumes:
            - ${VOLUME_REDIS_CONFIG}:/usr/local/etc/redis/redis.conf
        networks:
            - default
        ports: 
            - 6379:6379

    node:
        image: node:14.17.1-alpine
        container_name: local-node
        volumes:
            - ${VOLUME_WORKSPACE}:/srv
        working_dir: /srv
        command: tail -f /dev/null
        networks:
            - default

networks:
    default:
        driver: bridge