services:

    db:
        image: mysql:9.0.1
        container_name: ${MYSQL_CONTAINER_NAME}
        restart: always
        ports: 
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - ${MYSQL_VOLUME_DATABASE}:/var/lib/mysql
        networks:
            - default