services:

    db:
        image: mysql:8.0
        container_name: ${MYSQL_CONTAINER_NAME}
        restart: always
        ports: 
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - ${MYSQL_VOLUME_DATABASE}:/var/lib/mysql
        networks:
            - default

    nginx:
        image: nginx:1.27.0-alpine
        container_name: ${NGINX_CONTAINER_NAME}
        restart: always
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - ${WORKSPACE_FOLDER}:/var/www
            - ./sites-enabled:/etc/nginx/conf.d
        networks:
            - default

    php:
        image: php-laravel:11.1.4
        container_name: ${PHP_CONTAINER_NAME}
        restart: always
        working_dir: /var/www
        build:
            args:
                user: ${USER_NAME}
            context: ./php-8-3
            dockerfile: Dockerfile
        volumes:
            - ${WORKSPACE_FOLDER}:/var/www
            - ./php-config/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - default