services:
    angular:
        image: node-angular:18.1.3
        container_name: node-angular
        restart: always
        working_dir: /srv
        build:
            args:
                name: ${GIT_USER_NAME}
                email: ${GIT_USER_EMAIL}
            context: ./node-20-16-0
            dockerfile: Dockerfile
        volumes:
            - ${WORKSPACE_FOLDER}:/srv
        command: tail -f /dev/null
        ports: 
            - 4200:4200
        networks:
            - default